In [1]:
import numpy as np

In [26]:
def power(inpvector,n,increase=False):
    if increase==False:
        output=np.array([x**(n-1-i) for x in inpvector for i in range(n)]).reshape(inpvector.size,n)
    else:
        output=np.array([x**i for x in inpvector for i in range(n)]).reshape(inpvector.size,n)
    
    return output
        

In [41]:
l=np.array([1,2,3])
n=3
print(power(l,n,increase=True))
print("\n----------------\n")
print(power(l,n,increase=False))

[[1 1 1]
 [1 2 4]
 [1 3 9]]

----------------

[[1 1 1]
 [4 2 1]
 [9 3 1]]


In [77]:
def moving_average(values,k):
    if len(values)!=0 and k>0:
        values=values.cumsum()
        values[k:]=values[k:]-values[:-k]
        print("no of element: ",len(values)-k+1)
        return values[k-1:]/k
    
    else:
        print("enter a valid data")
        
        

In [78]:
a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [79]:
moving_average(a,3)

no of element:  11


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])